### ISSUE TITLE
运行提示错误：urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by bigoovip** [izumiChan16/clash_ini2sing-box#2]
有个很奇怪的问题，只要在ini文件中添加speedtest的规则集（如下），运行main.py就会提示“urllib.error.HTTPError: HTTP Error 403: Forbidden”，就算只有这一个规则集，都会出现这个问题；反之，只要没有这个规则集，运行就会成功生成config文件。

ruleset=Speedtest,https://raw.githubusercontents.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml

请教下，该如何解决呢？

CMD提示如下：
Traceback (most recent call last):
  File "D:\Users\clash_ini2sing-box-master\main.py", line 205, in <module>
    main()
  File "D:\Users\clash_ini2sing-box-master\main.py", line 186, in main
    rules_dict_list, no_group_rules_dict_list, final_value = generate_rules(rules_df, no_group_rules)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\clash_ini2sing-box-master\main.py", line 91, in generate_rules
    rules_dict = parse_list_file(rule)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\clash_ini2sing-box-master\main.py", line 59, in parse_list_file
    results = list(executor.map(read_csv_and_append, [list_links]))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\concurrent\futures\_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\concurrent\futures\_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\program\Python\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\clash_ini2sing-box-master\main.py", line 52, in read_csv_and_append
    return pd.read_csv(link, header=None, names=['pattern', 'address', 'other'], on_bad_lines='warn')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\site-packages\pandas\io\parsers\readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\site-packages\pandas\io\parsers\readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\site-packages\pandas\io\parsers\readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\site-packages\pandas\io\parsers\readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "D:\program\Python\Lib\site-packages\pandas\io\common.py", line 718, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\site-packages\pandas\io\common.py", line 372, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
         ^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\site-packages\pandas\io\common.py", line 274, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\urllib\request.py", line 553, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "D:\program\Python\Lib\urllib\request.py", line 745, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\Python\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "D:\program\Python\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by izumiChan16** [comment]
@yzbleaf 规则集应该用list文件，而不是yaml

https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list

**Comment by bigoovip** [comment]
> @yzbleaf 规则集应该用list文件，而不是yaml
> 
> https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list

谢谢回复，经测试，只有Speedtest.list这一条规则(如下)，仍然提示同样错误。
ruleset=Speedtest,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
另外，yaml文件只会引起转换的config中的route相关规则为空，但不会转换失败。

**Comment by bigoovip** [comment]
@izumiChan16 另外再请教下，list文件是哪个内核的规则格式，我记得clash应该是yaml文件格式。

**Comment by izumiChan16** [comment]
@yzbleaf 都是clash的，只是我这个代码没有做yaml provider的解析。而且ini配置文件大多是用list文件

**Comment by izumiChan16** [comment]
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/pref.ini

参考使用的比较多的ACL4SSR

**Comment by bigoovip** [comment]
> https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/pref.ini
> 
> 参考使用的比较多的ACL4SSR

谢谢，看到这个，忽然想起来，.list是后台转换的规则文件。
我改成https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list，可以成功生成config了。

**Comment by izumiChan16** [comment]
@yzbleaf  是的，以后subconverter也肯定会适配出sing-box的转换功能，到时应该也会基于通用配置文件模板。所以我也基于这个文件做了转换，实在是没有能力给subconverter提交PR，等待吧，这个暂且做临时工具用用
